export const commands = [
    // UTILS
    { name: "sticker", desc: "Convertir una imagen en sticker", alias: ["sticker", "s"], category: "utils" },
    { name: "pfp", desc: "Obtener la foto de perfil de alguien", alias: ["getpic", "pfp"], category: "utils", uso: "_<mention>_" },
    { name: "translate", desc: "Traducir un texto", alias: ["translate"], category: "utils", uso: "_<idioma>_ + _<texto>_" },
    { name: "get", desc: "Realizar una petición GET", alias: ["get"], category: "utils", uso: "_<url>_" },
    { name: "setmeta", desc: "Elegir el nombre del pack de stickers", alias: ["setmeta"], category: "utils", uso: "_<packname>_ + _<autor>_" },
    { name: "hd", desc: "Mejorar una imagen", alias: ["hd"], category: "utils" },
    { name: "tourl", desc: "Convertir una imagen en URL", alias: ["tourl"], category: "utils" },
    { name: "pendientes", desc: "Lista de pendientes personal/admins", alias: ["pendientes", "apendientes"], category: "utils" },
    { name: "padd", desc: "Agregar algo a la lista de pendientes", alias: ["padd", "apadd"], category: "utils", uso: "_<texto>_" },
    { name: "premove", desc: "Quitar algo de la lista de pendientes", alias: ["premove", "apremove"], category: "utils", uso: "_<índice>_" },
    { name: "brat", desc: "Crear un sticker a partir de un texto", alias: ["brat"], category: "utils", uso: "_<texto>_" },
    { name: "bratv", desc: "Crear un sticker animado a partir de un texto", alias: ["bratv"], category: "utils", uso: "_<texto>_" },
    { name: "toimage", desc: "Convierte un sticker en imagen", alias: ["toimage", "toimg"], category: "utils" },
    { name: "togif", desc: "Convierte un sticker animado en gif", alias: ["togif"], category: "utils" },

    // SEARCH
    { name: "ytsearch", desc: "Hacer una búsqueda por YouTube", alias: ["ytsearch", "search"], category: "search", uso: "_<texto>_" },
    { name: "ttsearch", desc: "Hacer una búsqueda por TikTok", alias: ["ttsearch", "tiktoksearch", "tts"], category: "search", uso: "_<texto>_" },
    { name: "imagen", desc: "Buscar una imagen por Google", alias: ["imagen", "img"], category: "search", uso: "_<texto>_" },

    // DOWNLOADS
    { name: "aptoide", desc: "Descargar un apk de Aptoide", alias: ["apk", "aptoide"], category: "downloads", uso: "_<texto>_" },
    { name: "pinterest", desc: "Descargar imágenes de Pinterest", alias: ["pinterest", "pin"], category: "downloads", uso: "_<url|query>_" },
    { name: "facebook", desc: "Descarga videos de facebook.", alias: ["facebook", "fb"], category: "downloads", uso: "_<url>_" },
    { name: "mediafire", desc: "Descarga archivos de mediafire.", alias: ["mediafire", "mf"], category: "downloads", uso: "_<query|url>_" },
    { name: "instagram", desc: "Descarga videos de instagram.", alias: ["instagram", "ig"], category: "downloads", uso: "_<url>_" },
    { name: "tiktok", desc: "Descarga videos de tiktok.", alias: ["tiktok", "tt"], category: "downloads", uso: "_<url|query>_" },
    { name: "ytmp3", desc: "Descarga audio de youtube.", alias: ["play", "mp3", "playaudio", "ytaudio", "ytmp3"], category: "downloads", uso: "_<url|query>_" },
    { name: "ytmp4", desc: "Descarga video de youtube.", alias: ["play2", "mp4", "playvideo", "ytvideo", "ytmp4"], category: "downloads", uso: "_<url|query>_" },

    // PREMIUM
    { name: "vip", desc: "Comprar rango VIP", alias: ["vip"], category: "premium", uso: "_<tiempo>_ + _<h|d|s|m>_" },
    { name: "supervip", desc: "Comprar rango SuperVIP", alias: ["supervip"], category: "premium", uso: "_<tiempo>_ + _<h|d|s|m>_" },
    { name: "ultravip", desc: "Comprar rango UltraVIP", alias: ["ultravip"], category: "premium", uso: "_<tiempo>_ + _<h|d|s|m>_" },

    // CASINO
    { name: "ruleta", desc: "Jugar a la ruleta", alias: ["rt", "roulette", "ruleta"], category: "casino", uso: "_<color|número|how>_ + _<apuesta>_" },
    { name: "blackjack", desc: "Jugar al BlackJack", alias: ["blackjack"], category: "casino", uso: "_<apuesta|how>_" },
    { name: "delbj", desc: "Eliminar partida de BlackJack", alias: ["delblackjack", "delbj"], category: "casino" },
    { name: "dados", desc: "Lanzar los datos", alias: ["dice", "dados"], category: "casino", uso: "_<número[1-6]|how>_ + _<apuesta>_" },
    { name: "dadosvip", desc: "Lanzar los datos Premium", alias: ["dadosvip", "dicevip"], category: "casino", uso: "_<apuesta|how>_" },
    { name: "crash", desc: "Jugar al Crash", alias: ["crash"], category: "casino", uso: "_<apuesta|how>_" },
    { name: "poker", desc: "Jugar al Poker", alias: ["poker"], category: "casino", uso: "_<apuesta>_" },
    { name: "delpoker", desc: "Eliminar partida de Poker", alias: ["delpoker"], category: "casino" },
    { name: "duelo", desc: "Jugar a la Ruleta Rusa", alias: ["duel", "duelo"], category: "casino", uso: "_<apuesta>_ + _<mención>_" },

    // ECONOMIA
    { name: "einfo", desc: "Ver tus tiempos de espera para los comandos", alias: ["einfo", "economyinfo"], category: "economia" },
    { name: "bal", desc: "Ver tu balance de dinero", alias: ["bal"], category: "economia" },
    { name: "baltop", desc: "Ver el top global de dinero", alias: ["baltop"], category: "economia" },
    { name: "gbaltop", desc: "Ver el top grupal de dinero", alias: ["gbaltop"], category: "economia" },
    { name: "withdraw", desc: "Sacar dinero del banco", alias: ["with", "withdraw"], category: "economia", uso: "_<cantidad>_" },
    { name: "deposit", desc: "Depositar dinero en el banco", alias: ["d", "deposit"], category: "economia", uso: "_<cantidad>_" },
    { name: "daily", desc: "Recompensa diaria", alias: ["daily", "diario"], category: "economia" },
    { name: "weekly", desc: "Recompensa semanal", alias: ["weekly", "semanal"], category: "economia" },
    { name: "monthly", desc: "Recompensa mensual", alias: ["monthly", "mensual"], category: "economia" },
    { name: "steal", desc: "Robarle dinero de la billetea a alguien", alias: ["steal"], category: "economia", uso: "_<mention>_" },

    // JUEGOS
    { name: "math", desc: "Problema matemático", alias: ["math"], category: "juegos", uso: "_<dificultad>_" },
    { name: "ppt", desc: "Jugar a Piedra, Papel o Tijeras contra el bot", alias: ["ppt"], category: "juegos", uso: "_<piedra|papel|tijeras>_" },
    { name: "guess", desc: "Jugar a Adivina el personaje", alias: ["guess"], category: "juegos" },

    // TRABAJOS
    { name: "work", desc: "Trabajar", alias: ["w", "work"], category: "trabajos" },
    { name: "slut", desc: "Prostituirse", alias: ["slut"], category: "trabajos" },
    { name: "crime", desc: "Cometer un crimen", alias: ["crime"], category: "trabajos" },
    { name: "mine", desc: "Trabajar en la mina", alias: ["mine"], category: "trabajos" },
    { name: "ritual", desc: "Hacer un ritual", alias: ["ritual"], category: "trabajos" },
    { name: "veterinary", desc: "Trabajar de veterinari@", alias: ["veterinario", "veterinary"], category: "trabajos" },
    { name: "sicary", desc: "Trabajar de sicari@", alias: ["sicary", "sicario"], category: "trabajos" },
    { name: "pilotogp", desc: "Correr una carrera de MotoGP o AutoGP", alias: ["pilotogp"], category: "trabajos" },
    { name: "medic", desc: "Trabajar de médico", alias: ["medic", "medico"], category: "trabajos" },
    { name: "forge", desc: "Trabajar de herrero", alias: ["forge", "forjar"], category: "trabajos" },
    { name: "cut", desc: "Trabajar de leñador", alias: ["cut", "talar"], category: "trabajos" },
    { name: "piloto", desc: "Trabajar de piloto de avión", alias: ["piloto"], category: "trabajos" },
    { name: "pimp", desc: "Trabajar de proxeneta", alias: ["chulo", "pimp"], category: "trabajos" },
    { name: "explore", desc: "Realizar una expedición", alias: ["explore", "explorar"], category: "trabajos" },
    { name: "hunt", desc: "Salir de caza", alias: ["hint", "cazar"], category: "trabajos" },
    { name: "dungeon", desc: "Entrar a una mazmorra", alias: ["dungeon", "mazmorra"], category: "trabajos" },
    { name: "adventure", desc: "Salir de aventuras", alias: ["adventure", "aventura"], category: "trabajos" },

// GACHA
    { name: "rollchar", desc: "Invocar un personaje libre", alias: ["rollchar", "rc"], category: "gacha" } ,
    {name: "claim", desc: "Comprar el personaje invocado", alias: ["claim", "c"], category: "gacha"},
    {name: "freedom", desc: "Ver los personajes sin dueño", alias: ["freedom", "libres"], category: "gacha", uso: "_<página>_"},
    {name: "charactershop", desc: "Mercado de personajes", alias: ["charshop", "cshop"], category: "gacha", uso: "_<página>_"},
    {name: "sell", desc: "Vender un personaje", alias: ["sell"], category: "gacha", uso: "_<precio>_ + _<personaje>_"},
    {name: "removesell", desc: "Cancelar la venta de un personaje", alias: ["removesale"], category: "gacha", uso: "_<personaje>_"},
    {name: "buy", desc: "Comprar un personaje", alias: ["buychar", "buyc"], category: "gacha", uso: "_<personaje>_"},
    {name: "gachalist", desc: "Ver la lista de juegos/series/personajes", alias: ["gachalist", "glist"], category: "gacha", uso:"_<categoria *|* all *|* serie>_ + _<página>_"},
    {name: "charinfo", desc: "Información e imagen de un personaje", alias: ["charinfo", "cinfo"], category: "gacha", uso: "_<personaje>_"},
    {name: "harem", desc: "Ver tu colección de personajes", alias: ["harem"], category: "gacha", uso: "_<página>_"},
    {name: "gachainfo", desc: "Ver tu información de gacha", alias: ["gachainfo", "ginfo"], category: "gacha"},
    {name: "trade", desc: "Intercambiar un personaje con otro usuario", alias: ["trade"], category: "gacha", uso: "_<personaje1>_ + _<personaje2>_"},
    {name: "chartop", desc: "Top de coleccionistas", alias: ["chartop", "ctop"], category: "gacha", uso: "_<página>_"},

    // REGALOS
    { name: "christmas", desc: "Regalo de navidad", alias: ["cgift", "christmas"], category: "regalos" },
    { name: "new year", desc: "Regalo de Año Nuevo", alias: ["nygift", "newyear"], category: "regalos" },
    { name: "valentine", desc: "Regalo de San Valentín", alias: ["vgift", "valentine"], category: "regalos" },
    { name: "easter", desc: "Regalo de Pascuas", alias: ["pgift", "easteregg"], category: "regalos" },
    { name: "goku", desc: "Regalo del día de Goku", alias: ["gkgift", "goku"], category: "regalos" },
    { name: "rosh hashana", desc: "Regalo de Año Nuevo Judío", alias: ["rhgift", "roshhashana"], category: "regalos" },
    { name: "halloween", desc: "Regalo de Halloween", alias: ["hgift", "halloween"], category: "regalos" },
    { name: "saint patrick", desc: "Regalo de San Patricio", alias: ["spgift", "patrickday"], category: "regalos" },
    { name: "Akira Toriyama", desc: "Regalo en memoria de Akira Toriyama", alias: ["tgift", "akiratoriyama", "toribot"], category: "regalos" },
    { name: "fools day", desc: "Regalo del día de los inocentes", alias: ["fgift", "fools"], category: "regalos" },
    { name: "wizard kings", desc: "Regalo de los Reyes Magos", alias: ["wkgift", "wizardkings"], category: "regalos" },

    // BROMAS
    { name: "infiel", desc: "El bot elige al azar un usuario casado y uno no casado", alias: ["infiel"], category: "bromas", uso: "" },
    { name: "chiste", desc: "El bot cuenta un chiste de la categoría elegida", alias: ["chiste", "joke"], category: "bromas", uso: "_<categoría>_" },
    { name: "sugjoke", desc: "Sugerir un chiste", alias: ["sugchiste", "sugjoke"], category: "bromas", uso: "_<chiste>_" },

    // IA
    { name: "ia", desc: "Preguntar a ChatGPT", alias: ["ia", "chatgpt"], category: "ia", uso: "_<texto>_" },

    // ANIME
    { name: "peek", desc: "Espiar a alguien.", alias: ["peek"], category: "anime", uso: "_<mention>_" }, 
    { name: "comfort", desc: "Consolar a alguien.", alias: ["comfort"], category: "anime", uso: "_<mention>_" },
    { name: "thinkhard", desc: "Pensar intensamente.", alias: ["thinkhard"], category: "anime", uso: "_<mention>_" },
    { name: "curious", desc: "Sentir curiosidad.", alias: ["curious"], category: "anime", uso: "_<mention>_" },
    { name: "sniff", desc: "Olfatear a alguien.", alias: ["sniff"], category: "anime", uso: "_<mention>_" },
    { name: "stare", desc: "Mirar fijamente.", alias: ["stare"], category: "anime", uso: "_<mention>_" },
    { name: "trip", desc: "Tropezar accidentalmente.", alias: ["trip"], category: "anime", uso: "_<mention>_" },
    { name: "blowkiss", desc: "Lanzar un beso.", alias: ["blowkiss"], category: "anime", uso: "_<mention>_" },
    { name: "snuggle", desc: "Acurrucarse con alguien.", alias: ["snuggle"], category: "anime", uso: "_<mention>_" },
    { name: "angry", desc: "Estar enojado.", alias: ["angry"], category: "anime", uso: "_<mention>_" },
    { name: "bleh", desc: "Sacar la lengua.", alias: ["bleh"], category: "anime", uso: "_<mention>_" },
    { name: "bored", desc: "Estar aburrido.", alias: ["bored", "aburrido"], category: "anime", uso: "_<mention>_" },
    { name: "clap", desc: "Aplaudir.", alias: ["clap"], category: "anime", uso: "_<mention>_" },
    { name: "coffee", desc: "Tomar café.", alias: ["coffee", "cafe"], category: "anime", uso: "_<mention>_" },
    { name: "cold", desc: "Mucho frío.", alias: ["cold"], category: "anime", uso: "_<mention>_" },
    { name: "sing", desc: "Cantarle a alguien.", alias: ["sing"], category: "anime", uso: "_<mention>_" },
    { name: "tickle", desc: "Hacer cosquillas.", alias: ["tickle"], category: "anime", uso: "_<mention>_" },
    { name: "scream", desc: "Gritar fuerte.", alias: ["scream"], category: "anime", uso: "_<mention>_" },
    { name: "push", desc: "Empujar a alguien.", alias: ["push"], category: "anime", uso: "_<mention>_" },
    { name: "nope", desc: "Expresar desacuerdo.", alias: ["nope"], category: "anime", uso: "_<mention>_" },
    { name: "jump", desc: "Saltar de felicidad.", alias: ["jump"], category: "anime", uso: "_<mention>_" },
    { name: "heat", desc: "Sentir calor.", alias: ["heat"], category: "anime", uso: "_<mention>_" },
    { name: "gaming", desc: "Jugar videojuegos.", alias: ["gaming"], category: "anime", uso: "_<mention>_" },
    { name: "draw", desc: "Hacer un dibujo.", alias: ["draw"], category: "anime", uso: "_<mention>_" },
    { name: "call", desc: "Llamar a alguien.", alias: ["call"], category: "anime", uso: "_<mention>_" },
    { name: "dramatic", desc: "Hacer un drama.", alias: ["dramatic", "drama"], category: "anime", uso: "_<mention>_" },
    { name: "drunk", desc: "Estar borracho.", alias: ["drunk"], category: "anime", uso: "_<mention>_" },
    { name: "impregnate", desc: "Embarazar.", alias: ["impregnate", "preg"], category: "anime", uso: "_<mention>_" },
    { name: "kisscheek", desc: "Besar en la mejilla.", alias: ["kisscheek", "beso"], category: "anime", uso: "_<mention>_" },
    { name: "laugh", desc: "Reírse.", alias: ["laugh"], category: "anime", uso: "_<mention>_" },
    { name: "love", desc: "Sentir atracción.", alias: ["love", "amor"], category: "anime", uso: "_<mention>_" },
    { name: "pout", desc: "Hacer pucheros.", alias: ["pout"], category: "anime", uso: "_<mention>_" },
    { name: "punch", desc: "Dar un puñetazo.", alias: ["punch"], category: "anime", uso: "_<mention>_" },
    { name: "run", desc: "Correr.", alias: ["run", "correr"], category: "anime", uso: "_<mention>_" },
    { name: "sad", desc: "Sentir tristeza.", alias: ["sad", "triste"], category: "anime", uso: "_<mention>_" },
    { name: "scared", desc: "Estar asustado.", alias: ["scared"], category: "anime", uso: "_<mention>_" },
    { name: "seduce", desc: "Seducir.", alias: ["seduce"], category: "anime", uso: "_<mention>_" },
    { name: "shy", desc: "Sentir timidez.", alias: ["shy", "timido"], category: "anime", uso: "_<mention>_" },
    { name: "sleep", desc: "Dormir.", alias: ["sleep"], category: "anime", uso: "_<mention>_" },
    { name: "smoke", desc: "Fumar.", alias: ["smoke", "fumar"], category: "anime", uso: "_<mention>_" },
    { name: "spit", desc: "Escupir.", alias: ["spit", "escupir"], category: "anime", uso: "_<mention>_" },
    { name: "step", desc: "Pisar.", alias: ["step", "pisar"], category: "anime", uso: "_<mention>_" },
    { name: "think", desc: "Pensar.", alias: ["think"], category: "anime", uso: "_<mention>_" },
    { name: "walk", desc: "Caminar.", alias: ["walk"], category: "anime", uso: "_<mention>_" },
    { name: "hug", desc: "Dar un abrazo.", alias: ["hug"], category: "anime", uso: "_<mention>_" },
    { name: "kill", desc: "Asesinar.", alias: ["kill"], category: "anime", uso: "_<mention>_" },
    { name: "eat", desc: "Comer.", alias: ["eat", "nom", "comer"], category: "anime", uso: "_<mention>_" },
    { name: "kiss", desc: "Dar un beso.", alias: ["kiss", "muak"], category: "anime", uso: "_<mention>_" },
    { name: "wink", desc: "Guiñar.", alias: ["wink"], category: "anime", uso: "_<mention>_" },
    { name: "pat", desc: "Dar una caricia.", alias: ["pat"], category: "anime", uso: "_<mention>_" },
    { name: "happy", desc: "Saltos de felicidad.", alias: ["happy", "feliz"], category: "anime", uso: "_<mention>_" },
    { name: "bully", desc: "Hacer bullying.", alias: ["bully"], category: "anime", uso: "_<mention>_" }, 
    { name: "bite", desc: "Morder.", alias: ["bite", "morder"], category: "anime", uso: "_<mention>_" },
    { name: "blush", desc: "Sonrojarse.", alias: ["blush"], category: "anime", uso: "_<mention>_" },
    { name: "wave", desc: "Saludar.", alias: ["wave"], category: "anime", uso: "_<mention>_" },
    { name: "bath", desc: "Bañarse.", alias: ["bath"], category: "anime", uso: "_<mention>_" },
    { name: "smug", desc: "Presumir.", alias: ["smug"], category: "anime", uso: "_<mention>_" },
    { name: "smile", desc: "Sonreír.", alias: ["smile"], category: "anime", uso: "_<mention>_" },
    { name: "highfive", desc: "Chocar los cinco.", alias: ["highfive"], category: "anime", uso: "_<mention>_" },
    { name: "handhold", desc: "Tomar de la mano.", alias: ["handhold"], category: "anime", uso: "_<mention>_" },
    { name: "cringe", desc: "Sentir cringe.", alias: ["cringe"], category: "anime", uso: "_<mention>_" },
    { name: "bonk", desc: "Golpear.", alias: ["bonk"], category: "anime", uso: "_<mention>_" },
    { name: "cry", desc: "Llorar.", alias: ["cry"], category: "anime", uso: "_<mention>_" },
    { name: "lick", desc: "Lamer.", alias: ["lick"], category: "anime", uso: "_<mention>_" },
    { name: "slap", desc: "Dar una bofetada.", alias: ["slap"], category: "anime", uso: "_<mention>_" },
    { name: "dance", desc: "Bailar.", alias: ["dance"], category: "anime", uso: "_<mention>_" },
    { name: "cuddle", desc: "Acurrucarse.", alias: ["cuddle"], category: "anime", uso: "_<mention>_" },
    { name: "respects", desc: "Press F to pay respects", alias: ["f", "respect"], category: "anime", uso: "_<mention>_" },

    // PROFILE
    { name: "level", desc: "Ver tu nivel y experiencia", alias: ["lvl", "level"], category: "profile" },
    { name: "marry", desc: "Casarse", alias: ["marry"], category: "profile", uso: "_<mention>_" },
    { name: "divorce", desc: "Divorciarse", alias: ["divorce"], category: "profile" },
    { name: "profile", desc: "Ver tu perfil", alias: ["profile", "perfil"], category: "profile" },
    { name: "description", desc: "Colocar una descripción en el perfil", alias: ["setdesc"], category: "profile", uso: "_<texto>_" },
    { name: "bithdate", desc: "Colocar tu fecha de cumpleaños", alias: ["setbirth"], category: "profile", uso: "_<dd/mm/aaaa>_" },
    { name: "hobby", desc: "Colocar tu hobby en tu perfil", alias: ["sethobby"], category: "profile", uso: "_<hobby>_" },
    { name: "genre", desc: "Colocar tu género", alias: ["setgenre"], category: "profile", uso: "_<hombre|mujer>_" },
    { name: "del description", desc: "Eliminar tu descripción", alias: ["deldesc"], category: "profile" },
    { name: "del birth", desc: "Eliminar tu cumpleaños", alias: ["delbirth"], category: "profile" },
    { name: "del genre", desc: "Eliminar tu género", alias: ["delgenre"], category: "profile" },

    // INFO
    { name: "infobot"